puppycompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from wtforms.widgets import TextInput


class BlogPostForm(FlaskForm):

    title = StringField('Whats on your mind : ', validators=[DataRequired()])
    text = TextAreaField('Tell us more about it : ', validators=[DataRequired()])
    submit = SubmitField('Spread the word')

puppycompanyblog/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from puppycompanyblog import db
from puppycompanyblog.models import BlogPost
from puppycompanyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)



@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )

@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

puppycompanyblog/core/views.py
from flask import render_template,request,Blueprint
from puppycompanyblog.models import BlogPost
from puppycompanyblog import weather

core = Blueprint('core',__name__)

@core.route('/')
def index():

    weatherApi = weather.weatherApi()
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    context={'blog_posts':blog_posts,'weather':weatherApi}
    return render_template('index.html',data=context)


@core.route('/info')
def info():

    return render_template('info.html')

puppycompanyblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from puppycompanyblog import db
from werkzeug.security import generate_password_hash,check_password_hash
from puppycompanyblog.models import User, BlogPost
from puppycompanyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from puppycompanyblog.users.picture_handler import add_profile_pic


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Logged in successfully.')

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

puppycompanyblog/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
</div>

{% endblock content %}

puppycompanyblog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
      <link href="../static/images/puppy.ico" rel="icon" type="image/x-icon" />
      <link rel="stylesheet" type= "text/css" href= "../static/master.css">
     <script src="../static/master.js"></script>
       <script src='https://kit.fontawesome.com/a076d05399.js'></script>
         <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/sharer.js/latest/sharer.min.js"></script>
        <script type="text/javascript">data = {{ data | safe }}</script>
      <meta charset="utf-8">
      <style>
  body {
    padding-top: 40px;
      padding-bottom: 60px;
      color: black;
  }
  .dark-mode {
  background-color: #303030;
  color: black;
}
  .dark-mode > div{
      color: black;
  }
  @media (max-width: 980px) {
    body {
      padding-top: 0;
    }

  }

</style>
      <script>
function myFunction() {
   var element = document.body;
   element.classList.toggle("dark-mode");
}
</script>
    <title></title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('core.index') }}">
    <img src="../static/images/pupLogo.JPG" width="100" height="35" alt="">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('core.index') }}">Home <i class="fas fa-home"></i> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('core.info') }}">About-Us <i class="fas fa-address-card"></i></a>
      </li>
         {% if current_user.is_authenticated %}
    <li class="nav-item active"><a class="nav-link" href="{{ url_for('users.logout') }}">Log-Out<i class="fas fa-sign-out-alt"></i></a></li>
    <li class="nav-item active"><a class="nav-link" href="{{ url_for('users.account') }}">Account <i class="fas fa-user-circle"></i></a></li>
    <li class="nav-item active"><a class="nav-link" href="{{ url_for('blog_posts.create_post') }}">Spread-Love <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-suit-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="color:red">
  <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
</svg></a></li>
    {% else %}
    <li class="nav-item active"><a class="nav-link" href="{{ url_for('users.login') }}" >Log-In <i class="fas fa-sign-in-alt"></i></a></li>
    <li class="nav-item active"><a class="nav-link" href="{{ url_for('users.register') }}">Sign-Up <i class="fas fa-user-plus"></i></a></li>
    {% endif %}
      <script>
            var domainroot=""
            function Gsitesearch(curobj){ curobj.q.value=""+domainroot+" "+curobj.qfront.value }
    </script>
  <li class="nav-item active" id="google">
          <form class="form-inline my-2 my-lg-0" action="http://www.google.com/search" method="get"role="search" onSubmit="Gsitesearch(this)">
        <div class="input-group"> <input name="q" type="hidden" />
        <input class="form-control" name="qfront" type="search" required class="searchField" placeholder="Google Site Search" maxlength="50"/>
        <span class="input-group-btn">
            <button type="submit" class="search-button btn btn-primary" style="margin-left: 2px">
                <span class="glyphicon glyphicon-search"></span> Enter </button> </span>
        </div>
    </form>
  </li>
          <li class="nav-item active"><button onclick="myFunction()" class='btn btn-secondary pushme' data-default-text="Too much light!" data-new-text="Now i cant see!" id="lightdark" >Too much light!</button></li>
      <script>
        $(".pushme").click(function () {
            var $element = $(this);
            $element.text(function(i, text) {
                return text == $element.data('default-text') ? $element.data('new-text')
                                                            : $element.data('default-text');
            });
        });
    </script>

      </ul>
    </div>
  </nav>

  <div class="container">
  {% block content %}

  {% endblock %}
</div>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom" id="footer">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <p class="btn btn-outline-danger" class="navbar-nav mr-auto">Made With <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-suit-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
</svg> for <i class="fas fa-dog"></i> </p>

                        <ul class="navbar-nav ml-auto weather" id="weather">

                     <li class="nav-item active" id="time" > <a class="nav-link "  id="time"></a></li>
                     <li class="nav-item" id="date"> <a class="nav-link "  id="date"></a></li>
                        </ul>
     <ul class="navbar-nav ml-auto">
    <h4 class="btn btn-secondary disabled">Follow us on :</h4>
         <li class="nav-item "><a class="nav-link mr-1" href="https://www.facebook.com/?stype=lo&jlou=Afc40hZvlpfSzPBsR_8npWdXeYLAeb0elS9yZuKqLnnEOPUGup3Ly1kv2K22HLsiOh6BvbdlkuXlu8TCic5TQm6LPGXTesJ0S_R7g9BlIzgnAw&smuh=14992&lh=Ac9ZC4uV8uN6VzmF" style="color:#3b5998"><i class="fa fa-facebook"></i></a></li>
         <li class="nav-item "><a class="nav-link mr-1" href="https://twitter.com/krishna71873" style="color:#00acee"><i class="fa fa-twitter"></i></a></li>
         <li class="nav-item "><a class="nav-link mr-1" href="https://www.instagram.com/krishna71873/" style="color:#3f729b"><i class="fa fa-instagram"></i></a></li>
         <li class="nav-item "><a class="nav-link mr-1" href="https://in.linkedin.com/in/krishna-dumpala-b61a6b11a" style="color:#0e76a8"><i class="fa fa-linkedin"></i></a></li>
         <li class="nav-item "><a class="nav-link mr-1" href="https://github.com/10540452" style="color:black"><i class="fa fa-github"></i></a></li>
         </ul>
    </div>
</nav>

<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous">
  </script>
  </body>
</html>

puppycompanyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user or current_user == 'admin' or current_user == '10540452@mydbs.ie' %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>


  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

puppycompanyblog/templates/index.html
{% extends "base.html" %}
{% block content %}
    <head>
    <link href= "../static/index.css" rel="stylesheet" type= "text/css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <script src="../static/index.js"></script>
</head>
    <body style="margin-top: 25px">
<div class="alert alert-primary alert-dismissible fade show" role="alert" align="center">
  <div class="container">
    <ul class="list-inline">
        <li class="list-inline-item "><p>Weather in</p></li>
                    <li class="list-inline-item "><span class="title"><strong>{{ data.weather.city }}</strong></span></li>
                    <li class="list-inline-item"> <span class="subtitle">is <strong> {{ data.weather.temperature }}° C</strong></span></li>
                    <li class="list-inline-item"> <span class="description">with {{ data.weather.description }}</span></li>

        <li class="list-inline-item"> <div class="media-left" >
                                    <figure class="image is-50x50" style="width: auto; height: 0px" >
                                        <img src="http://openweathermap.org/img/w/{{data.weather.icon }}.png"  alt="Image">
                                    </figure>
                              </div></li>
        <li class="list-inline-item"><p>, but clearly you are hotter!!!</p></li>
<script>
    $(document).ready(function () {

window.setTimeout(function() {
    $(".alert").fadeTo(1000, 0).slideUp(1000, function(){
        $(this).remove();
    });
}, 5000);

});
</script>

  </ul>
      </div>

</div>

  <div class="jumbotron">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" >
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="../static/images/slider1.JPG" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
    <h5>“If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man.”
</h5>
    <p>― Mark Twain</p>
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="../static/images/slider2.JPG" alt="Second slide">
        <div class="carousel-caption d-none d-md-block">
    <h5 >“The world would be a nicer place if everyone had the ability to love as unconditionally as a dog.” </h5>
    <p >― M.K. Clinton</p>
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="../static/images/slider3.JPG" alt="Third slide">
        <div class="carousel-caption d-none d-md-block">
    <h5>“A dog is the only thing on earth that loves you more than he loves himself.” </h5>
    <p>— Josh Billings</p>
  </div>
    </div>
       <div class="carousel-item">
      <img class="d-block w-100" src="../static/images/slider4.JPG" alt="Fourth slide">
           <div class="carousel-caption d-none d-md-block">
    <h5 >“If there are no dogs in Heaven, then when I die I want to go where they went.” </h5>
    <p >— Will Rogers</p>
  </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
  </div>
  <div class="container">


    {% for post in data.blog_posts.items %}

<div class="row">
    <div class="col-sm-12">
        <div class="card" >
            <div class="card-body" >
                    <h2><a class="card-title" href=" {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
                    <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
                    <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
                    <p class="card-text">{{ post.text[:100] }}...</p>
                    <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
            </div>
        </div>
    </div>
</div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in data.blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if data.blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
     </ul>
    </nav>
  </div>
    </body>
{% endblock %}

puppycompanyblog/templates/login.html
{% extends "base.html" %}
{% block content %}
    <head>
        <link rel="stylesheet" type= "text/css" href="../static/login.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/sharer.js/latest/sharer.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    </head>

    <body>

        <div id="logreg-forms">
            <form class="form-signin" method="POST">
                {{ form.csrf_token }}
                <h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Sign in </h1>
                {{ form.email(placeholder="Email") }}<br>
                {{ form.password(class="form-control",placeholder="Password") }}<br>
                {{ form.submit(placeholder="Sign in") }}
                <a href="mailto:10539269@mydbs.ie" id="forgot_pswd">Forgot password?</a>
                <p> Send us a mail and we will reset it for you.</p>
            <hr>

                <button href="{{ url_for('users.register',filename ='/register') }}" class="btn btn-primary btn-block" type="button" id="btn-signup">
                    <i class="fas fa-user-plus"></i> Sign up New Account</button>
            </form>
            <a href="{{url_for('core.index') }}" id="cancel_signup"><i class="fa fa-angle-left"></i> Back</a>


    </div>
    </body>
{% endblock %}

puppycompanyblog/templates/register.html
{% extends "base.html" %}

{% block content %}

         <form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}<br>
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.pass_confirm.label }} {{ form.pass_confirm() }}<br>
    {{ form.submit() }}

</form>

{% endblock %}

puppycompanyblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endblock content %}